### ISSUE TITLE
Please enable logging for reposado syncing

### ISSUE THREAD

**Issue by ski98033** [jamf/NetSUS#1]
I hacked this in your adminHelper.sh file, but there is a proper way to do it from within the sync command.  This is needed to debug and verify syncing is working.

**Comment by MScottBlake** [comment]
This would be a great feature.

My NetSUS is not pulling the 10.10.4 update and I have no idea why. If logging were enabled, I might be able to discern the problem.

**Comment by maccy10** [comment]
I'd also love to get an email notification after a successful automatic sync (or something to tell me it has gone wrong).

**Comment by macmule** [comment]
I believe the OP's issues was addressed in: https://github.com/jamf/NetSUS/commit/607f60e5655733d10ac5a7650f5944dd8fc51b40, so will close this off

**Comment by jelockwood** [comment]
I am not seeing any options in NetSUS 4.2.1 for accessing or configuring the log for Reposado i.e. the SUS portion of NetSUS.

For what it's worth the location of Reposado on a NetSUS appliance is /var/lib/reposado the preference file for reposado is therefore at /var/lib/reposado/preferences.plist

As per a standard Reposado install it should be possible to configure Reposado to use a separate log file at the location of your choice by editing that file and adding the entry - 

<key>RepoSyncLogFile</key>
<string>/var/log/reposado_sync.log</string>

As far as I can see the webadmin interface for NetSUS will list any log in /var/log so if as per the above example XML you tell Reposado to create its log in /var/log it should hopefully then show up in the drop-down menu in the NetSUS webadmin interface.
