### ISSUE TITLE
Unable to load NBImageInfo.plist - Deploy-studio created NBI

### ISSUE THREAD

**Issue by TPGeek** [jamf/NetSUS#100]
Currently we are investgating using NetSUS to replace OSX's NetInstall in the next few months, but our NBI image or even a freshly generated image is providing me with the error.

> WARNING: Unable to read NBImageInfo.plist default values are being used

This is preventing us from using NetSUS for Netboot functionality at this stage.
![image](https://user-images.githubusercontent.com/17175575/37494102-568cb3f8-289f-11e8-93b1-3bf08cb865e7.png)

**Comment by kdu2** [comment]
it currently only works with Casper's nbi and Imagr. You used to be able to get DSR nbi's to work by editing a file that checks for the nbi, but that no longer works with the latest release (see rich trouton's blog).

**Comment by duncan-mccracken** [comment]
Deploy Studio creates the NBIImageInfo.plist in binary form, which isn't understood by python (what the NetSUS uses in the back end to read to plist.
You have two options:
1. Convert the NBIImageInfo.plist to xml form prior to uploading, on a macOS system execute the following command:
`plutil -convert xml1 /path/to/NBIImageInfo.plist `
2. Edit the info in the page displayed above and save it, this will create a new NBIImageInfo.plist with the appropriate data in xml form.

**Comment by jitman** [comment]
I'll have to say Duncan is wrong about DS creating the NBImageInfo.plist file in binary form.  I have DS 1.7.8 in operation and after creating a fresh NetBoot set I'm able to open the file in TextWrangler with no issues and it all looks xml to me.

Even so, I've tried running the command in option 1 as suggested with no success.

Option 2 does something, but I had to delete the file first.  After a few attempts, the file was recreated with almost identical settings as the original but I still see the above warning.  The file was also created with `root` user and group ownership whereas the rest are owned by my server's `smbuser`.

Here's the weird part: my NetBoot set works!  I just had to delete the `NetInstall.dmg` shortcut created my DS and save the changes through the NetSUS interface.  This changes the `RootPath` key to `NetInstall.sparseimage`.

Overall this seems like some kind of permissions issue.  I've attached a screenshot of what the file's rights are according to terminal right after copying to the NetBoot share.  Hope it helps.

![2018-06-14_09-42-37](https://user-images.githubusercontent.com/20727481/41426279-fd2b2fa0-6fb7-11e8-90d3-80b698bb3f41.jpg)

**Comment by sebaslag** [comment]
I have the same problem: WARNING: Unable to read NBImageInfo.plist default values are being used.
Sometimes I can boot using NetSUS and sometimes the progress bar never ends. I tried to change the permissions but without success. Does anyone have the solution? Thank you

**Comment by aaronyeung** [comment]
Can confirm that deleting NetInstall.dmg seems to make it work and boot up the DS NBI but the error in the console still persists.

**Comment by MorphZan** [comment]
Has anyone succeeded with this.
I have installed Netsus and uploaded a DS NBI which I can select but halfway through loading the target machine reboots.... Any Suggestions?

**Comment by duncan-mccracken** [comment]
Addressed in latest release

**Comment by nmors** [comment]
Having this same issue in the latest NetSUS release, image created from latest Mojave using Imagr. Ubuntu 18.04.

Options suggested did not work, tried @duncan-mccracken suggestions. Stuck on message "Unable to read NBImageInfo.plist. Edit the Image to correct this issue" however, editing the image via webUI does not seem to do anything at all. The file exists with appropriate permissions
