### ISSUE TITLE
Unable to create CSR

### ISSUE THREAD

**Issue by kdu2** [jamf/NetSUS#101]
I get an HTTP error 500 when clicking create after I enter a subdomain for our internal domain, e.g. netsus.domain.com (it's not an actual .com for internal). I'm running NetSUS 4.2.1 via the install script on Ubuntu 16.04. where should I be looking to troubleshoot this? Netboot is working great. not using Software Update Server at the moment.

**Comment by kitzy** [comment]
I'm having this issue as well, also running 4.2.1 via the install script on Ubuntu 16.04

**Comment by duncan-mccracken** [comment]
It seems the php zip extension isn't installed by default in Ubuntu 16
Short term fix is to simply install the extols manually:
sudo apt-get install php7.0-zip
This will be added to the installation script in the next release.

**Comment by duncan-mccracken** [comment]
Addressed in latest release
