### ISSUE TITLE
.run installer doesn't run to completion if IPv6 is disabled - tftpd-hpa related issue

### ISSUE THREAD

**Issue by tlcarpenter** [jamf/NetSUS#102]
I tried to install NetSUS (.run installer) on a system running Xubuntu 16.04.4 LTS (amd64); the installer started but stopped at the point where "Starting Web Application Installation" was displayed. 'applianceinstaller.log' entries showed that 'tftpd-hpa' wasn't starting, e.g.

Job for tftpd-hpa.service failed because the control process exited with error code.

and

ExecStart=/etc/init.d/tftpd-hpa start (code=exited, status=71)

The long story short is that I disabled IPv6 in /etc/default/grub by specifying

GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1"

and running 'update-grub'. Apparently tftpd-hpa doesn't like this

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=690535

but can be reconfigured to support IPv4 only - I used the configuration provided
by Nicolas Mattard-Michaud in the Debian Bug report above, editing
/etc/default/tftpd-hpa to read

TFTP_USERNAME="tftp"
TFTP_DIRECTORY="/var/lib/tftpboot"
TFTP_ADDRESS="0.0.0.0:69"
TFTP_OPTIONS="-4 --secure"

I should add that after attempting the initial installation of NetSUS, when I didn't realize tftpd-hpa wasn't starting, I was able to access the web interface and do some configuration. The web interface seemed to hang, for example, if I went to the "Settings" tab, selected one of the items, either under "NetBoot/SUS/LDAP Proxy Server" or "Shares", and then clicked the "Back" button,
the web interface was either unresponsive or incredibly slow, and I just didn't wait long enough.

After configuring /etc/default/tftpd-hpa as described above, I ran the .run installer again and it appears to have successfully run to competion.

**Comment by duncan-mccracken** [comment]
Configuration option has been added to installation process for the next release

**Comment by duncan-mccracken** [comment]
Addressed in latest release
