### ISSUE TITLE
Please update documentation for CentOS installs

### ISSUE THREAD

**Issue by vphan13** [jamf/NetSUS#103]
I installed NetSUS on a minimal CentOS 7.4.  I have a few items that I think should be documented

1. After a sucessful install, the webui is incredibly slow, and there are 9 branches 
sudo:
no:
tty:
present:
and:
no:
askpass:
program:
specified:

This issue is fixed by adding the following to my sudoers file

`apache hostname=(ALL) NOPASSWD: /bin/sh scripts/adminHelper.sh *`

as suggested in the following forum thread
https://www.jamf.com/jamf-nation/discussions/13564/just-had-a-linux-sus-netboot-vm-built-have-you-seen-this-error

This is a common error dating back to 2015

2. Can the documents be updated to include where the reposado files are installed?  I had to hunt down the repoutil and plist preferences file installed under /var/lib/reposado. . 
3. Include in documentation the default location where the metadata and updates will be stored.  Not everyone is going to want to create a giant vmdk to house this data. . .I know this can be set using the repoutil command. . but see second issue above

Lastly is there anyway to specify another path for the reposado files?  This would make a docker container much easier to create

**Comment by duncan-mccracken** [comment]
Addressed in latest release
