### ISSUE TITLE
NetSUS site finds downloads, but computers don't

### ISSUE THREAD

**Issue by el2493** [jamf/NetSUS#107]
I'm able to login to our NetSUS web interface and enable updates there (and click Apply).  But if I then go to a computer that is configured for the NetSUS server and open the App Store, it doesn't find any updates that I've enabled.  How long should it take for computers to see the updates, and what can I do to troubleshoot if it's not working?

**Comment by el2493** [comment]
Update: It's now working for Sierra computers, but on High Sierra it gives an error mesage that it can't load data.  I'm on v4.2.1, if I do a `defaults read` command it shows:

http://[netsusrul]/content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1_[branch].sucatalog

If I change it to the Sierra Branch (just delete "10.13-"), it finds updates and doesn't give any error.  I just updated to 4.2.1 a little while ago, do I need to run any commands to restart anything?

**Comment by duncan-mccracken** [comment]
Addressed in latest release
