### ISSUE TITLE
Feature Request: Patch Server for Jamf Pro

### ISSUE THREAD

**Issue by matviyko** [jamf/NetSUS#108]
Productivity and patch management usually don't go hand-in-hand with the third-party apps + services I support...especially those binaries that burn red-hot, week after week, through company vulnerability scanning/audits.

Just recently, I found @brysontyrrell's [superb implementation of a patch manager](https://github.com/brysontyrrell/PatchServer) that integrates with Jamf Pro's external API. The overhead is frighteningly nominal and just feels like it would be a perfect fit within the umbrella of NetSUS.

Feature request for the integration of these two godsends!

**Comment by duncan-mccracken** [comment]
Try this:
https://mondada.github.io/

**Comment by matviyko** [comment]
Wicked, thank you for your craft!!
