### ISSUE TITLE
webadmin login 

### ISSUE THREAD

**Issue by Binog** [jamf/NetSUS#109]
Hey, is there anything wrong?
I booted up the ovt image, it said welcome and told me to user webadmin as username and password,. but the login is incorrect. have no idea why!? 
Anyone?

**Comment by duncan-mccracken** [comment]
Just checking you are trying to log into the web interface?
`https://<netsus ip or hostname>/webadmin/`
If you need to reset the web admin password back to the default, it can be done by logging into the console (or ssh) using the `shelluser` account (see: docs > accounts.md) for details)
The commands to reset the webadmin password are:
`sudo cp -p /var/appliance/conf/appliance.conf.xml /var/appliance/conf/appliance.conf.xml.bak`
`sudo sed -i 's:<webadminuser>.*</webadminuser>::' /var/appliance/conf/appliance.conf.xml`
`sudo sed -i 's:<webadminpass>.*</webadminpass>::' /var/appliance/conf/appliance.conf.xml`
Refresh the login page in your browser, you will be able to use the defaults.
