### ISSUE TITLE
Web interface unusable in Safari

### ISSUE THREAD

**Issue by jelockwood** [jamf/NetSUS#112]
NetSUS 4.1 rendered and worked fine in Safari. I was properly able to see the user interface and utilise it. With NetSUS 5.0 it is now not rendering properly with elements not visible and hence is effectively unusable in Safari. An example screen capture is included.

![screen shot 2018-10-01 at 10 24 45](https://user-images.githubusercontent.com/4300786/46280748-a0348c80-c564-11e8-8bf6-7ed00b1297cf.png)

It does render properly in Google Chrome on a Mac and also Firefox on a Mac.

**Comment by duncan-mccracken** [comment]
Hi @jelockwood,
From the screenshot above, it simply looks as if safari has the old cached.
It can be one of a few issues, which are reasonably easy to resolve.
In Safari go to Preferences > Advanced and enable the Devep menu
Once this is done, load the NetSUS dashboard in a browser.
Use the key combo cmd-option-a to show the page resources.
Double-click the file styles.css in the resources list, it should open in a new tab
Close the resource inspector and refresh the page.
If this doesn't work, I noticed in development that the server-side cache in apache was sometimes holding on to the previous version's stylesheet.
If this happens:
Quit safari
Connect to the NetSUS using ssh
Issue the following two commands to stop and start Apache (note: issuing a restart isn't always successful):
  `sudo service apache2 stop`
  `sudo service apache2 start`
Open safari and connect to the NetSUS

**Comment by jelockwood** [comment]
Yep, clearing the Safari cache cured it.

You can close this issue. Thanks!
