### ISSUE TITLE
Can't add users

### ISSUE THREAD

**Issue by macchrister** [jamf/NetSUS#116]
Hi, I can't add users the add button is not active and I can't change password for afpuser and smbuser.

**Comment by duncan-mccracken** [comment]
The '+Add' button is for adding Active Directory Groups, once the Active Directory configuration is added.
There are plans for the ability to add additional webadmin users, but this is not yet implemented.
You should be able to reset the afpuser/smbuser passwords by selecting the 'Reset Password' option when clicking on the usernames.
The 'Modify User' option is disabled as certain services expect these accounts to be in a specific configuration.

**Comment by macchrister** [comment]
It seams like shelluser is not created when using centos7.
