### ISSUE TITLE
SSL CA Bundle missing

### ISSUE THREAD

**Issue by blawbkps** [jamf/NetSUS#118]
Hi! When I create the 'Certificate Signing Request' the download that is zipped up only contains the certreq.csr and private.key. The CA Bundle file is missing and therefore cannot be put into 'Modify Certificates' and applied as a new SSL cert. Is the CA Bundle sent somewhere else I should be looking?

Thanks!

**Comment by TwoTwenty** [comment]
The CA bundle should not be required, its for when you use an actual certificate authority to create your cert via the CSR.

**Comment by duncan-mccracken** [comment]
The CSR is used to create your signed certificate, with whatever CA you decide to use.
The CA you use should supply you with the CA bundle or chain, when you create the certificate
You then upload the Private key, created certificate and CA bundle.
Does this make sense?
