### ISSUE TITLE
How to use the NetBoot server to Boot

### ISSUE THREAD

**Issue by vmarlier** [jamf/NetSUS#121]
Hi,

I have installed NetSUS on a server and enable File Sharing and NetBoot and I've add an .nbi to the NetBoot server.
But right now I don't know what to do..
I've start the MacBook Pro 2016 without touchbar (client) in recovery mode with hope to find the server anywhere but I can't find it..

Can you update you're wiki and add a section to the NetBoot like "How to use it" ^^

Thanks ;)

**Comment by vilva42** [comment]
I would also appreciate an update to the docs.
