### ISSUE TITLE
cannot apply SSL certificates

### ISSUE THREAD

**Issue by TwoTwenty** [jamf/NetSUS#123]
Hello,

I just installed NetSUS using NetSUSLPInstaller_5.0.run on a RHEL7 box 
all has gone well so far I can access the interface, changed all  passwords, restarted the server etc. 

I have also put our wildcard cert in the system /etc/pki/tls/... and changed the ssl.conf to get our proper cert working for the admin interface. 

I cannot apply that certificate from the web interface the apply button is crossed out when I hover the mouse over.

my cert/key is pem formatted wihtout encryption and I have the begin end lines

**Comment by ewtillman** [comment]
Just my experience but maybe it will help you.
I used the ova but converted it to hyper-v.
On the cert screen in the web gui once you put in key information it likes the borders will no longer be red, and when you get all 3 the apply will unlock.
I had to convert my private key to RSA and then it worked.
openssl rsa -in domain.key -out domain-rsa.key

**Comment by TwoTwenty** [comment]
that was the answer thanks

openssl rsa -in domain.key -out domain-rsa.key
