### ISSUE TITLE
NetSUS across VLANs

### ISSUE THREAD

**Issue by dfuriet** [jamf/NetSUS#134]
Hi everybody

How to use NetSUS v5 across VLANs ? We are on Cisco networks.
In old NetSUS 4.2 we could add subnet, add ip range in dhcp config file and use Cisco "ip helper-address x.x.x.x" where x.x.x.x is netsus server address in the vlan where are my macs

But with NetSUS v5, it's doesn't work.

Thank you in advance for helping
D. FURIET

**Comment by duncan-mccracken** [comment]
Hi Damien,

This issue was brought to my attention a little while ago, and will addressed in a pending (almost complete) update for NetSUS, allowing you to select the new (pybsdp) or old (dhcpd) engines for broadcasting NetBoot.

Hoping to have this finished within the next week.

~Duncan

**Comment by dfuriet** [comment]
OK, good news ! 
I will wait impatiently this new version !

Bye

**Comment by arusso** [comment]
Any news on when this might be released?

**Comment by davearre** [comment]
Second that request - I just set up a NetSus to allow our school district to netinstall Mojave on our fleet of Macs and just discovered the lack of response when clients are on a separate subnet. It works perfectly on the same subnet. I would appreciate a workaround or fix to allow us to deploy in our labs.

Thanks!

**Comment by a-silaev** [comment]
Same here. Can't wait for the update.

**Comment by duncan-mccracken** [comment]
Hey All,
I'm currently finalising the code for this update, couple of minor bugs to squash, and then it should be good to go. I'll try to get it out ASAP.
~Duncan

**Comment by duncan-mccracken** [comment]
Hi All,

I have a release candidate available for NetSUS 5.0.1, some additional testers would be greatly appreciated, prior committing the final changes to the main repo.
For a list of changes, please visit (the docs are also up-to-date here):
https://github.com/mondada/NetSUS/blob/master/CHANGELOG.md

Installer and OVA are (temporarily) available at:
https://www.dropbox.com/s/ypzcmu0088h7gvy/NetSUSLPInstaller_5.0.1.run
https://www.dropbox.com/s/8keatnjke5w7bjd/NetSUSLP_5.0.1.ova

Thanks,
~Duncan
