### ISSUE TITLE
CentOS 6.5: netatalk and dependencies are not installed successfully during NetSUS standalone installation.

### ISSUE THREAD

**Issue by trevorwagner** [jamf/NetSUS#23]
If NetSUS standalone is installed under a clean installation of CentOS 6.5 without first installing dependencies for netatalk, I'm observing output that appears to indicate both that the dependencies are not being installed as expected and that netatalk fails to install as expected.  

I'm observing some output in the command line that appears to indicate that dependencies for netatalk are not being satisfied:

```
/usr/bin/perl is needed by netatalk-4:2.2.0-2.el6.x86_64
libavahi-client.so.3()(64bit) is needed by netatalk-4:2.2.0-2.el6.x86_64
libavahi-common.so.3()(64bit) is needed by netatalk-4:2.2.0-2.el6.x86_64
perl(File::Basename) is needed by netatalk-4:2.2.0-2.el6.x86_64
perl(File::Spec) is needed by netatalk-4:2.2.0-2.el6.x86_64
perl(IO::Socket) is needed by netatalk-4:2.2.0-2.el6.x86_64
perl(Socket) is needed by netatalk-4:2.2.0-2.el6.x86_64
perl(bigint) is needed by netatalk-4:2.2.0-2.el6.x86_64
perl(strict) is needed by netatalk-4:2.2.0-2.el6.x86_64
perl(vars) is needed by netatalk-4:2.2.0-2.el6.x86_64
```

In the very last line of output from the installer script, I'm also seeing an error message that appears to indicate that it was not possible to run netatalk (because the command does not exist at the path specified in the script):

```NetSUSInstaller.sh: line 186: /etc/init.d/netatalk: No such file or directory```

### Steps to Reproduce

1. Run a clean installation of CentOS 6.5.  Make sure all available updates have been applied with yum.

2. Per the instructions in the User Guide, install NetSUS from the standalone installer.

3. Watch the output returned by the installer for the error messages I outline above.

### Notes

Netatalk is required to serve AFP from Linux, so to me (unless I'm missing something) it looks like this behavior likely breaks AFP access on a NetSUS server (where all of the STR are satisfied).  I'm not familiar with NetBoot at all, but from my experience with netatalk (and some very-cursory research I did on DIY NetBoot servers in Linux), it seems like it might be worth understanding as well whether this could potentially affect netboot.  If anybody with more experience in this area has any input, it seems like it might be helpful.

I was able to find [some instructions to install netatalk 2.2.0 (the release it looks like NetSUS normally uses) here](http://rathelm.wordpress.com/2012/02/03/cent-os6-2-and-netatalk-2-2-0/).  If I install all dependencies other than `rpm-build` (which didn't seem relevant) between steps 1 and 2 in the STR I've provided, I'm able to install NetSUS successfully with netatalk (and I'm able to verify that netatalk is running as expected).

I'm not sure what the full dependency tree is for netatalk, but here is the command I run to make it work:

`# yum install {openssl,pam,db4,libgcrypt,avahi,libacl,openldap,cracklib,quota,tcp_wrappers}-devel libtool avahi`

~~I did not observe this at all under Ubuntu (LTS Server versions 12.04 and 10.04).~~ In Ubuntu LTS Server 12.04 I observe that netatalk is not being installed (reported as #32).  Under Ubuntu LTS Server 10.04, I'm observing that netatalk is installing as expected.

I do not currently have a copy of RHEL 6.4 (or later) that I can test this with.  If at all possible, I recommend testing for this behavior under RHEL, as well.

It might also be worth noting that I reproduced this in a VirtualBox (v 4.3.10 r93012) virtual machine, with a host machine running under OS X 10.9.1.

**Comment by StevenStrand** [comment]
Could not reproduce.
