### ISSUE TITLE
Ubuntu LTS 12.04: Apache/ httpd does not appear to be installed with the NetSUS standalone installer.

### ISSUE THREAD

**Issue by trevorwagner** [jamf/NetSUS#24]
If NetSUS standalone is installed under a clean installation of Ubuntu LTS Server 12.04, apache/ httpd is not installed at the time NetSUS is.  There are four things I'm seeing that seem to support this conclusion:

- If I attempt to access WebAdmin after installing (or after installing then rebooting), Chrome and cURL return messages that they were not able to access the server (cURL tells me the connection was refused).

- If I attempt to start apache/ httpd from the command line (`# /etc/init.d/apache2 start`) after running the installer, the command line returns an error message that it could not find the command issued.

- If I attempt to locate either apache or httpd with `$ pgrep -l <keyword>`, pgrep returns no results.

- The folder /etc/apache2 does not exist after the installer has run.  In Ubuntu this is the path where binary- and config files for apache/ httpd are stored.

### Steps to Reproduce

1. Run a clean installation of Ubuntu LTS Server 12.04.  Make sure all available updates have been applied with aptitude.

2. Per the instructions in the User Guide, install NetSUS from the standalone installer.

3. Attempt to connect to WebAdmin.  The server refuses the connection.  

4. Try any of the other methods listed above.

### Notes

When I tested this, I addressed #22 between steps 1 and 2.  So I ran a clean installation of Ubuntu, addressed #22, and proceeded to run the installer.

I'm only reproducing this under version 12.04.  I'm not able to reproduce this issue under Ubuntu LTS Server 10.04.  I'm also not reproducing this under CentOS.  I do not currently have a copy of RHEL 6.4 (or later) that I can test this with.  

At one point earlier, I thought I was able to install successfully (and access WebAdmin) under 12.04 without reproducing this behavior.  This was before I started keeping records of my testing, though, so I might be remembering incorrectly.  If somebody else would be willing to take a look at this, though, before assigning to the developer, we should be able to determine whether it seems like what I remember here seems correct.

It might also be worth noting that I reproduced this in a VirtualBox (v 4.3.10 r93012) virtual machine, with a host machine running under OS X 10.9.1.

**Comment by StevenStrand** [comment]
Closed, could not reproduce.
