### ISSUE TITLE
After syncing SUS with Apple, Server > Last Sync displays a date that appears consistently incorrect.

### ISSUE THREAD

**Issue by trevorwagner** [jamf/NetSUS#26]
On the Software Update Server page (in NetSUS WebAdmin), the value `Mar 17` displays consistently **Last Sync:**, regardless of which day today's date is.

### Steps to Reproduce

1. Run NetSUS (ideally, on a server that is fully updated).

2. From a Web browser, access NetSUS WebAdmin on the server.

3. From the WebAdmin sidebar, select **Software Update Server**.

4. On the Software Update Server page, click **Sync Manually**.

5. If no value appears at first under **Last Sync:**, refresh the page in the Web browser.

Once I follow these steps, I'm observing that `Mar 17` displays consistently as the value for  **Last Sync:**.

### Notes

I reproduce this behavior with servers running under CentOS 6.5 and under Ubuntu LTS Server 10.04.  I was not able to test with a server running Ubuntu LTS Server 12.04 due to #24.

Every time I reproduced this behavior, I also navigated to Settings > Date & Time and confirmed that the timestamp returned by Date & Time matched the current local system time.

I've tested this each of the last three calendar days.  Each day the value that displays is March 17th.

I've reproduced this in Chrome for Mac (version 34.0.1847.131) and Safari 7.0.3 (9537.75.14), under OS X 10.9.1.  I have not attempted to reproduce this yet with any other Web browsers.  To me it seems like this could be a limited sample group; by testing with more browsers (and on additional platforms), it seems like it should be possible to increase the sample group (and determine whether it might appear that the reproducibility of this behavior is limited by either browser or platform).

It might also be worth noting that when I reproduced this, CentOS and Ubuntu were (each) running in a (separate) VirtualBox (v 4.3.10 r93012) virtual machine, with a host machine running under OS X 10.9.1.

**Comment by StevenStrand** [comment]
Closed, cannot reproduce in current release.
