### ISSUE TITLE
NFS instead of HTTP

### ISSUE THREAD

**Issue by henrycoule** [jamf/NetSUS#38]
How do I change how the boot image is sent over to the client from http to NFS? I am trying to use the bless command to remote reboot the client machine into netboot mode but it only works so far with NFS and NetSUS is sending the netboot image using http

**Comment by franton** [comment]
Unlikely as Apple themselves are deprecating Netboot via NFS

**Comment by macmule** [comment]
@henrycoule I'm closing this off. 

With bless being depreciated largely with csrutil in SIP on 10.11+ PLUS NFS under a netboot service tends to cause issues as the port changes.

Keeping http for the latter is better as a static port.
