### ISSUE TITLE
cannot extract backup.tar.gz downloaded from backup.php

### ISSUE THREAD

**Issue by macbofh** [jamf/NetSUS#39]
When i download a backup using the URL: https://NETSUS/webadmin/backup.php i cannot extract the backup.tar.gz file. I downloaded the file using Safari, Firefox and Chrome and tried to extract it using the terminal (tar -zxvf), stuffit expander, The unarchiver, GUI Tar.

**Comment by duncan-mccracken** [comment]
Addressed in latest release
