### ISSUE TITLE
Bonded NIC cards NetBoot will not start

### ISSUE THREAD

**Issue by mks-007** [jamf/NetSUS#43]
After following the bonding process from https://help.ubuntu.com/community/UbuntuBonding

The Web console and smb sharing work fine but the NetBoot service will not start.

Could this be added to the network settings or a workaround be found

**Comment by duncan-mccracken** [comment]
Bonded NICs are not supported in the GUI, however if you upgrade to version 5, the bonded interfaces will be available for NetBoot
