### ISSUE TITLE
Can't Enable Netboot

### ISSUE THREAD

**Issue by sliq** [jamf/NetSUS#47]
the /etc/dhcpd.conf file is doing weird things and the values inside it are not updating accordingly.

You can manually edit the values to make it work but once you go to Webadmin and press Enable Netboot it reverts back to those weird values.

I have tested this on a fresh install and an upgrade on Ubuntu 14.04. 
This was happening on the appliance as well.

**Comment by macmule** [comment]
Having an issue enabling NetBoot here too, awk--version returns: GNU Awk 4.0.1.

app-get advises that latest version is installed.

**Comment by justinrummel** [comment]
I've mentioned there were a couple of commands missing from the setup script (vs. ova): https://github.com/jamf/NetSUS/issues/50#issue-50862507

**Comment by macmule** [comment]
FWIW, mine was a separate issue: https://github.com/jamf/NetSUS/issues/53

**Comment by StevenStrand** [comment]
Resolved with 4.0.0
