### ISSUE TITLE
Ubuntu Server 14.04.1 "command sestatus not found"

### ISSUE THREAD

**Issue by justinrummel** [jamf/NetSUS#50]
Newly created 14.04.1 Ubuntu server from linux.iso, only configured a couple of network settings (/etc/hosts, /etc/hostname, /etc/network/interfaces) restart then curled down the .run file... I see this error at the beginning. 

> NetSUSInstaller.sh: line 107: sestatus: command not found

Don't know if there needs to be a line to validate prior to 107 to see if sestatus is available.  Ubuntu suggested to run "sudo apt-get install policycoreutils" to resolve.

**Comment by agh** [comment]
Looks like its assuming (`sestatus`) that you're on an EL-based platform?

**Comment by macmule** [comment]
I've been having a nose around, & below are the lines where your were getting the error in the NetSUSInstaller.sh:

if sestatus | grep -q enforcing ; then
	logEvent "Setting SELINUX mode to permissive"
	echo "A restart of the system will be required before using the NetSUS"
	sed -i "s/SELINUX=enforcing/SELINUX=permissive/" /etc/selinux/config
fi

Would encapsulating the above in a IF loop like the below work?

if [ -f "/usr/sbin/sestatus" ]; then

**Comment by macmule** [comment]
Never mind, should have seen the pull requests: https://github.com/jamf/NetSUS/pull/52

**Comment by justinrummel** [comment]
You're so damn helpful all the time! 

Btw, after running the scoot it does work... But not sure about the user experience of installing two items prior to the "we're ready to start installing".  

May move the lines of code somewhere else further down the process.
