### ISSUE TITLE
Please change NetBoot to BSDPy

### ISSUE THREAD

**Issue by MScottBlake** [jamf/NetSUS#55]
Please change from the current implementation of NetBoot to support BSDPy.

Making this change would allow the NetSUS to host multiple NBIs as well as display the real name of the NBI instead of "Faux NetBoot"

**Comment by franton** [comment]
Already an FR for it :) https://jamfnation.jamfsoftware.com/featureRequest.html?id=1969

**Comment by macmule** [comment]
Hi @MScottBlake, this isn't likely with NetSUS as it is.. but might be coming in another form.

You know where to find me if want to know more.
