### ISSUE TITLE
Cant Install on RHEL 6.4

### ISSUE THREAD

**Issue by xcutionr45** [jamf/NetSUS#59]
Cant install NetSUS on RHEL 6.4. The OS set is setup a bit different than normal. 
No Sudoers file. Root access is granted another way. 
I cannot acquire compat-db47 through my current repo. This appears to be where the installer script bombs out.
 
Here is the installation procedure:

[root@<hostname> tmp]# ./NetSUS_3.0.2.run 
Verifying archive integrity... All good.
Uncompressing NetSUS Installer............
Starting the NetSUS Installation
Checking installation requirements...
Checking for a supported OS...This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
RedHat
Checking for a 64-bit OS...OK
Passed all requirements checking!

Is this a standalone installation?
Answer yes unless you are creating an image of the appliance to deploy in multiple locations

Standalone?  (y/n): n

The following will be installed
* Appliance Web Interface
* NetBoot Server
* Software Updates Server

Proceed?  (y/n): t
Proceed?  (y/n): y
Installing...
Verifying archive integrity... All good.
Uncompressing WebAdmin Installer.......................................................................................................................................................................................................
Starting Web Application Installation
iptables: Saving firewall rules to /etc/sysconfig/iptables:[  OK  ]
sed: can't read /etc/sudoers: No such file or directory
webadminInstall.sh: line 145: /etc/sudoers.d/webadmin: No such file or directory
chmod: cannot access `/etc/sudoers.d/webadmin': No such file or directory
Restarting apache...
OK
Finished deploying the appliance web application
Verifying archive integrity... All good.
Uncompressing NetBoot Installer..............................
Starting NetBoot Installation
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Error: Nothing to do

**Comment by xcutionr45** [comment]
Here is the contents of the log file 
[2015-08-31 18:11:10]: Starting the NetSUS Installation
[2015-08-31 18:11:10]: Checking installation requirements...
[2015-08-31 18:11:10]: Checking for a supported OS...
[2015-08-31 18:11:11]: RedHat
[2015-08-31 18:11:11]: Checking for a 64-bit OS...
[2015-08-31 18:11:11]: OK
[2015-08-31 18:11:11]: Passed all requirements checking!
[2015-08-31 18:11:23]: Installing...
[2015-08-31 18:11:23]: Starting Web Application Installation
[2015-08-31 18:11:26]: Restarting apache...
Stopping httpd:                                            [  OK  ]
Starting httpd:                                            [  OK  ]
[2015-08-31 18:11:27]: OK
[2015-08-31 18:11:27]: Finished deploying the appliance web application
[2015-08-31 18:11:27]: Starting NetBoot Installation
dhcpd: no process killed
[2015-08-31 18:11:33]: OK
[2015-08-31 18:11:33]: Finished deploying NetBoot

**Comment by StevenStrand** [comment]
Looks like your Red Hat server is not registered.  That would hinder the installation of services.

<code>This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.</code>

**Comment by xcutionr45** [comment]
Thanks. I will look into that.
