### ISSUE TITLE
Catalogs are not being properly generated when not caching updates (Centos 7 installer 4.0)

### ISSUE THREAD

**Issue by duel007** [jamf/NetSUS#63]
Tested on a fully up to date Centos 7 install. The various catalogs (index-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog and so on) are not generated by default when the NetSUS is installed via the installer package when choosing to not cache updates.

This issue is not present in the 3.02 OVA,4.0 OVA, or the 3.02 installer, but I am able to duplicate it on Centos 7 using the installer. Manually adding the apple catalogs to /var/lib/reposado/preferences.plist resolves the issue but this probably should still be addressed somehow.

**Comment by duncan-mccracken** [comment]
Addressed in latest release
