### ISSUE TITLE
Ability to Restrict Advertisement of Netboot

### ISSUE THREAD

**Issue by kubman007** [jamf/NetSUS#67]
Have we given any thought to adding the feature of restricting the Netboot to only be available to certain MAC addresses, like we can do in Apple's Netinstall service?  This could be handy in testing environments where multiple NetSUS's are set up and advertising.

**Comment by macmule** [comment]
@kubman007 The current implementation doesn't play well with other NetBoot servers on the same network.

So no, this is not something I can see being added.
