### ISSUE TITLE
Can't NetBoot on CentOS or RedHat

### ISSUE THREAD

**Issue by goldsmcb** [jamf/NetSUS#74]
It seems the NetBoot does not work properly on CentOS or RedHat. When trying to boot to the advertised NetBoot image a flashing globe appears on the client screen, after which it just boots to the hard disk. I am able to get it working on Ubuntu with the same image, the only difference being a spinning globe instead of a flashing one and it boots to the NetBoot image successfully. The /etc/dhcpd.conf file is exactly the same across OS's and all necessary files have the right privileges.

A unique log message I saw on the CentOS 7 server (`/var/log/messages | grep dhcpd`)

`dhcpd: DHCPACK to <client-ip> <mac-address> via eno167777736`
`dhcpd: DHCPINFORM from <client-ip> via eno167777736`
`dhcpd: <company-name>-DHCP change`
`dhcpd: N Key or encapsulated`
`dhcpd: 68`

I got nowhere trying to find the cause of this log message and I can't seem to find the cause of the issue anywhere in the NetSUSLP code.

**Comment by jtrutwin** [comment]
I am having the same problem on a RHEL 7.2 fresh install of NetSUS 4.1.0

When attempting to netboot the user sees a blinking folder with a question mark.  We see similar output in /var/log/messages though I don't know if this indicates any error or not.

Is there an alternate log file to check for issues?

Thanks, 

Josh

**Comment by goldsmcb** [comment]
I wasn't able to find another spot where relevant logs show up. I know this is not new to 4.1.0 as it did not work on 4.0.0 either, unless anyone else was able to get it working on CentOS/RedHat prior to 4.1.0.

**Comment by tylerwinfield** [comment]
CentOS 6.7 with NetSUS 4.1.0 having the same issue. NetBoot clients are able to see the image and attempt to load.  According to tcpdump traces, booter file is the last to be requested.

13:35:50.748608 IP (tos 0x0, ttl 64, id 53204, offset 0, flags [none], proto UDP (17), length 91)
    10.75.232.12.hecmtl-db > <servername>.tftp:_  63 RRQ "NetBoot_ElCapitan.nbi/i386/booter" octet tsize 0 blksize 2048
13:35:50.749613 IP (tos 0x0, ttl 64, id 53205, offset 0, flags [none], proto UDP (17), length 91)
    10.75.232.12.pciarray > <servername>.tftp:  63 RRQ "NetBoot_ElCapitan.nbi/i386/booter" octet tsize 0 blksize 2048
13:35:50.770567 IP (tos 0x0, ttl 64, id 53206, offset 0, flags [none], proto UDP (17), length 91)
    10.75.232.12.sna-cs > <servername>.tftp:  63 RRQ "NetBoot_ElCapitan.nbi/i386/booter" octet tsize 0 blksize 2048
13:35:50.771504 IP (tos 0x0, ttl 64, id 53207, offset 0, flags [none], proto UDP (17), length 91)
    10.75.232.12.caci-lm > <servername>.tftp:  63 RRQ "NetBoot_ElCapitan.nbi/i386/booter" octet tsize 0 blksize 2048

**Comment by manicslothpdx** [comment]
Do we know if this does work on CentOS 7 at all? I am now having issues similar to those listed above and, before digging too deeply, I guess it might be helpful to hear from someone who can verify that this is supposed to work. This is what I see when tailing the log as soon and I click on the NetBoot image:

`DHCPREQUEST for 10.126.97.224 from 00:3e:e1:c2:39:ee via 10.126.96.1: unknown lease 10.126.97.224.
2016-08-30T22:06:13.181422+00:00 caspershare-pdx dhcpd: DHCPINFORM from 10.126.96.97 via 10.126.96.1
2016-08-30T22:06:13.181596+00:00 caspershare-pdx dhcpd: JAMF-DHCP change
2016-08-30T22:06:13.181885+00:00 caspershare-pdx dhcpd: N Key or encapsulated
2016-08-30T22:06:13.182044+00:00 caspershare-pdx dhcpd: 68
2016-08-30T22:06:13.182180+00:00 caspershare-pdx dhcpd: DHCPACK to 10.126.96.97 (b8:ca:3a:b9:35:d0) via eth0`

**Comment by manicslothpdx** [comment]
And, I'm nearly certain it's not environmental because the older Ubuntu-based version of the NetSUS VM worked in this same location on our network with the same IP (in order to remove as many variables as possible.) Only the newer version running on CentOS 7 (for me in my environment) seems to have this issue.

**Comment by manicslothpdx** [comment]
I figured it out at least for my environment (CentOS 7.) Even if SELinux is set to permissive, you may have to perform some additional steps.

http://www.bo-yang.net/2015/08/31/centos7-install-tftp-server

More specifically, use these commands to check and modify the SELinux TFTP status:

getsebool -a | grep tftp

On mine, the results were:

tftp_anon_write --> off
tftp_home_dir --> off

So I turned them these on with the following commands:

setsebool -P tftp_anon_write 1
setsebool -P tftp_home_dir 1
And my results are now:

tftp_anon_write --> on
tftp_home_dir --> on

Afterwards, I immediately was able to NetBoot. As a side note, I was able to ignore the yum commands in step 1. I already had TFT and I didn't need XINETD. Your environment may vary.

**Comment by manicslothpdx** [comment]
Additionally, I had to alter the an additional file. I got this info from JAMFNation:

https://jamfnation.jamfsoftware.com/discussion.html?id=21033

Open in your text editor of choice: /lib/systemd/system/tftp.service

Modify this line: ExecStart=/usr/sbin/in.tftpd -s /srv/NetBoot/NetBootSP0

**Comment by duncan-mccracken** [comment]
Addressed in latest release
