### ISSUE TITLE
Ran out of space. Can't get into web portal

### ISSUE THREAD

**Issue by danshaw** [jamf/NetSUS#80]
So it happened. The VM drive I have set up is completely full with updates and I can no longer get into the web portal. I've tried SSH'ing into the VM and running the purge on deprecated files, but that has not created any space.

repoutil --purge-product all-deprecated --force

So I am at a loss. One question I do have is that currently I have 3 branches (beta, dev, and prod). If I have multiple branches does that mean that it downloads 3 copies of all the files? One for each branch.

The VM HD is set to 300GB like it was suggested. I am unsure how it filled up so fast.

Any help would be appreciated!

**Comment by seabash** [comment]
@danshaw I have also been seeing this behavior, which has occurred on three of my v4.1.0 NetSUS boxes.

My NetSUS env are all RHEL 7, serving only two branches.

For an interim, temp fix you should be able to delete a couple payloads, which will then allow you to log into web interface.  Here's an example of removal items to try...

`# First, confirm your free disk space...
df -H
# Then move into SUS content directories...
cd /srv/SUS/html/content/downloads
# List by date and select oldest 2-digit directories to delete (at bottom). We'll use an example of 49 rm -fR /srv/SUS/html/content/downloads/49
# Recheck free disk space
dh -H
# Try to log into NetSUS web interface again
# Or remove the next-oldest directory, if still cannot login.`

Again, this is a stopgap for currently-afflicted NetSUS instances.  There must be something w/ 4.1.0 to cause runaway disk consumption?

**Comment by seabash** [comment]
UPDATE: the minimum disk requirements should be updated _from_ 300GB to **350-400GB**?

Another brand-new NetSUS 4.1.0 instance (same specs as above) ran out of space within 24 hrs.
Moving the SUS data to an additional (non boot) volume avoided the issue of being unable to log into webapp, but it still filled-up the 300GB volume, preventing remaining updates from SUS (namely macOS Sierra and newer items).  So...
I expanded the SUS volume to 500GB and SUS now has all content, and has consumed a total of **344GB**.

Hope this helps anyone else being too frugal on SUS volume-sizing.

**Comment by macmule** [comment]
500GB should be the new requirements.

I'll look to update them.

**Comment by macmule** [comment]
Updated the readMe.. i know it's a bit too late to fix this on the affected server, but 500GB should be fine. 300GB is too small.
