### ISSUE TITLE
Updated for 10.12 

### ISSUE THREAD

**Issue by cvangorp** [jamf/NetSUS#81]
Please update so 10.12 macOS Sierra updates show up.  Just updated to 4.1 and it doesn't display 10.12.1 update posted.

**Comment by dalmatian1231** [comment]
same issue here.  our Netsus is not updating the branch since 10.12.2 released last week.  any solution?

**Comment by Jamyn** [comment]
If JAMF would review and approve pull request https://github.com/jamf/NetSUS/pull/83 from January 23rd ...

**Comment by macmule** [comment]
Hi folks,

Support was added with 4.2.1, so closing this off.
