### ISSUE TITLE
NetSus for 10.12 not showing Deprecated updates on client

### ISSUE THREAD

**Issue by hartleya** [jamf/NetSUS#82]
This seems to be an odd issue.
When I log into my instance of NetSUS, I have the options to activate deprecated updates such as macOS update 10.12.1. (we are not ready to go to 10.12.2).

However, when I check the sucatalog, its not written there.
 i.e.: If I only activate the 10.12.1 update, there is nothing in the SUCATALOG. This is the same for ANY deprecated updates.
In contrast, if I only activate the 10.12.2 update, which is not deprecated, the information is written in the sucatalog. So I know that the URL is correct for 10.12 as the updates in the catalog are showing up as available to the client.

Any ideas?

**Comment by duncan-mccracken** [comment]
Addressed in latest release
