### ISSUE TITLE
ERROR: Unable to start NetBoot service. Ensure your .nbi directory is properly configured

### ISSUE THREAD

**Issue by meyersdrums** [jamf/NetSUS#84]
I set the password for the SMB User and added a .NBI file I created in AutoCasperNBI.  I added a subnet that has a helper address pointing to the NetBoot server.  Once this was configured, I tried to start the NetBoot service and keep getting this error.  Do you have any suggestions to what I can do to get it running?  The server is running Ubuntu 14.04.4.  Thanks!

**Comment by macmule** [comment]
@meyersdrums Can for post a screenshot or ls output of your NBI directory that's been uploaded to NetSUS?

**Comment by meyersdrums** [comment]
Ben,

I figured it out.  I had the entire folder in the NetBoot folder instead of the .NBI file.

Thanks,

Mike
