### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by el2493** [jamf/NetSUS#89]
Is there a way to check the SSL Certificate through the GUI?  I took over a JAMF incidence from a previous tech and got a notification that the SSL Certificate was going to expire for the NetSUS server.  We got a replacement one and a Server technician believes it is updated, but I couldn't find any way to confirm that through the GUI.  In JSS there's a clear area which lists the Certificate that's installed and says when it's going to expire, but couldn't find any way through NetSUS.

I found the "Certificates" area in Settings, but when I clicked into that it's just blank fields.  I tried copying and pasting the data from the .cer file I have and clicking to Save, but then it just blanked all the fields and still doesn't show any information about the current certificate.

Thanks,.

**Comment by mondada** [comment]
The SSL Cert is also used for the Web UI.
Simply Visit the Web UI in a browser and click the little padlock for certificate details.

**Comment by duncan-mccracken** [comment]
Additionally certificate info will now be displayed in the Certificates UI in the next release.

**Comment by duncan-mccracken** [comment]
Addressed in latest release
