### ISSUE TITLE
Run file for 4.2.1 does not update on CENTOS

### ISSUE THREAD

**Issue by cmcMac** [jamf/NetSUS#92]
Tested only with CentOS.
Downloaded run file to ~/Desktop
chmod +X run file 
Run Run file and appears to update 
sudo reboot now 
check webgui still on 4.1.0

**Comment by cmcMac** [comment]
CentOS 7

**Comment by mondada** [comment]
Can you please post the contents of '/var/appliance/logs/applianceinstaller.log'

**Comment by cmcMac** [comment]
![screen shot 2017-11-30 at 3 36 58 pm](https://user-images.githubusercontent.com/17626519/33460750-7573e34e-d5e4-11e7-8d3a-5c69bdb5679c.png)
![screen shot 2017-11-30 at 3 30 45 pm](https://user-images.githubusercontent.com/17626519/33460569-a334222c-d5e3-11e7-8dec-69c5f8bea40d.png)

**Comment by mondada** [comment]
You have a conflicting version of php installed in this system.
Also you have a dead (custom) repo.

The NetSUS is designed to install on a dedicated system, using the standard CentOS repos with EPEL.
Given the literally hundreds of variations on php, the installer can't be made to cater for everything.

This isn't an issue with the NetSUS, but with the baseline you are attempting to install on having additional software from custom sources. The 4.1.0 installer did not exit on install failures.

You can attempt to remove the conflicting items, reconfigure the yum repos, back to default, the re-run the installer.

I would, however, suggest running NetSUS on a dedicated, headless system.

For reference, here is a list of everything the installer will attempt to install on CentOS (some of these may not be present in different release versions (i.e. 6 or 7), the installer does have logic to check for the package prior to attempting install:
Webadmin:
- python-pycurl
- parted
- dmidecode
- psmisc
- dialog
- m2crypto
- ntpdate
- mod_ssl
- php
- php-xml
- php-ldap
NetBoot:
- avahi
- samba
- samba-client
- tftp-server
- nfs-utils
- vim-common
SUS:
- mod_ssl
- php
- php-xml
LDAP Proxy:
- openldap-servers
- expect

**Comment by cmcMac** [comment]
I was able to get it installed after removing php5.6.  After that my new issue is the updates exist on the system but they are not advertising to the suscatalog.

**Comment by macmule** [comment]
@cmcMac please open another issue in regards to the SUSCatalog one.
