### ISSUE TITLE
NetSUS does not update to 4.2.1 using .run file Ubuntu 14.04.5 LTS

### ISSUE THREAD

**Issue by bbenkle** [jamf/NetSUS#95]
We are currently running NetSUS version 4.1 and when I run the 4.2.1 installer:

Verifying archive integrity... All good.
Uncompressing NetSUSLP Installer.................................................................................................................
Starting the NetSUS Installation
Checking installation requirements...
Checking for a 64-bit OS...OK
Checking for a supported OS...Ubuntu 14.04.5 LTS found
Checking for required Ubuntu binaries...OK
Passed all requirements

The following will be installed
* Appliance Web Interface
* Software Update Server
* NetBoot Server
* LDAP Proxy

Proceed?  (y/n): y
Installing...
Starting Web Application Installation

At this point the installer stops and bring me back to the main prompt in terminal.

When I execute the .run file with the --confirm argument I receive:

sudo ./NetSUSLPInstaller_4.2.1.run --confirm
Verifying archive integrity... All good.
About to extract 10152 KB in /tmp/selfgz8756 ... Proceed ? [Y/n] y
Uncompressing NetSUSLP Installer.................................................................................................................
OK to execute: bash install.sh   ? [Y/n] y
Starting the NetSUS Installation
Checking installation requirements...
Checking for a 64-bit OS...OK
Checking for a supported OS...Ubuntu 14.04.5 LTS found
Checking for required Ubuntu binaries...OK
Passed all requirements

The following will be installed
* Appliance Web Interface
* Software Update Server
* NetBoot Server
* LDAP Proxy

Proceed?  (y/n): y
Installing...
Starting Web Application Installation
The program 'bash install.sh' returned an error code (1)

Any insight would be very helpful.

**Comment by mondada** [comment]
Can you please post the contents of '/var/appliance/logs/applianceinstaller.log'

**Comment by bbenkle** [comment]
2017-11-30 13:56:03]:  Starting the NetSUS Installation
[2017-11-30 13:56:03]:  Checking installation requirements...
[2017-11-30 13:56:03]:  Checking for a 64-bit OS...
[2017-11-30 13:56:03]:  OK
[2017-11-30 13:56:03]:  Checking for a supported OS...
[2017-11-30 13:56:03]:  Ubuntu 14.04.5 LTS found
[2017-11-30 13:56:03]:  Checking for required Ubuntu binaries...
Ign http://us.archive.ubuntu.com trusty InRelease
Get:1 http://us.archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Hit http://us.archive.ubuntu.com trusty-backports InRelease
Hit http://us.archive.ubuntu.com trusty Release.gpg
Hit http://us.archive.ubuntu.com trusty Release
Get:2 http://us.archive.ubuntu.com trusty-updates/main Sources [409 kB]
Get:3 http://us.archive.ubuntu.com trusty-updates/restricted Sources [6,322 B]
Get:4 http://us.archive.ubuntu.com trusty-updates/universe Sources [196 kB]
Get:5 http://us.archive.ubuntu.com trusty-updates/multiverse Sources [7,740 B]
Get:6 http://us.archive.ubuntu.com trusty-updates/main amd64 Packages [1,040 kB]
Get:7 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
Get:8 http://us.archive.ubuntu.com trusty-updates/restricted amd64 Packages [17.2 kB]
Get:9 http://us.archive.ubuntu.com trusty-updates/universe amd64 Packages [435 kB]
Get:10 http://us.archive.ubuntu.com trusty-updates/multiverse amd64 Packages [14.9 kB]
Get:11 http://us.archive.ubuntu.com trusty-updates/main i386 Packages [982 kB]
Get:12 http://us.archive.ubuntu.com trusty-updates/restricted i386 Packages [17.0 kB]
Get:13 http://us.archive.ubuntu.com trusty-updates/universe i386 Packages [434 kB]
Get:14 http://us.archive.ubuntu.com trusty-updates/multiverse i386 Packages [15.3 kB]
Hit http://us.archive.ubuntu.com trusty-updates/main Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/multiverse Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty-updates/universe Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/main Sources
Hit http://us.archive.ubuntu.com trusty-backports/restricted Sources
Hit http://us.archive.ubuntu.com trusty-backports/universe Sources
Hit http://us.archive.ubuntu.com trusty-backports/multiverse Sources
Hit http://us.archive.ubuntu.com trusty-backports/main amd64 Packages
Hit http://us.archive.ubuntu.com trusty-backports/restricted amd64 Packages
Hit http://us.archive.ubuntu.com trusty-backports/universe amd64 Packages
Hit http://us.archive.ubuntu.com trusty-backports/multiverse amd64 Packages
Hit http://us.archive.ubuntu.com trusty-backports/main i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/universe i386 Packages
Get:15 http://security.ubuntu.com trusty-security/main Sources [147 kB]
Hit http://us.archive.ubuntu.com trusty-backports/multiverse i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/main Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/multiverse Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty-backports/universe Translation-en
Hit http://us.archive.ubuntu.com trusty/main Sources
Hit http://us.archive.ubuntu.com trusty/restricted Sources
Hit http://us.archive.ubuntu.com trusty/universe Sources
Hit http://us.archive.ubuntu.com trusty/multiverse Sources
Hit http://us.archive.ubuntu.com trusty/main amd64 Packages
Hit http://us.archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://us.archive.ubuntu.com trusty/universe amd64 Packages
Hit http://us.archive.ubuntu.com trusty/multiverse amd64 Packages
Hit http://us.archive.ubuntu.com trusty/main i386 Packages
Hit http://us.archive.ubuntu.com trusty/restricted i386 Packages
Hit http://us.archive.ubuntu.com trusty/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty/multiverse i386 Packages
Hit http://us.archive.ubuntu.com trusty/main Translation-en
Hit http://us.archive.ubuntu.com trusty/multiverse Translation-en
Hit http://us.archive.ubuntu.com trusty/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty/universe Translation-en
Ign http://us.archive.ubuntu.com trusty/main Translation-en_US
Ign http://us.archive.ubuntu.com trusty/multiverse Translation-en_US
Ign http://us.archive.ubuntu.com trusty/restricted Translation-en_US
Ign http://us.archive.ubuntu.com trusty/universe Translation-en_US
Get:16 http://security.ubuntu.com trusty-security/restricted Sources [4,931 B]
Get:17 http://security.ubuntu.com trusty-security/universe Sources [67.1 kB]
Get:18 http://security.ubuntu.com trusty-security/multiverse Sources [3,195 B]
Get:19 http://security.ubuntu.com trusty-security/main amd64 Packages [694 kB]
Get:20 http://security.ubuntu.com trusty-security/restricted amd64 Packages [14.1 kB]
Get:21 http://security.ubuntu.com trusty-security/universe amd64 Packages [197 kB]
Get:22 http://security.ubuntu.com trusty-security/multiverse amd64 Packages [4,795 B]
Get:23 http://security.ubuntu.com trusty-security/main i386 Packages [637 kB]
Get:24 http://security.ubuntu.com trusty-security/restricted i386 Packages [13.9 kB]
Get:25 http://security.ubuntu.com trusty-security/universe i386 Packages [195 kB]
Get:26 http://security.ubuntu.com trusty-security/multiverse i386 Packages [4,935 B]
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Fetched 5,689 kB in 5s (980 kB/s)
Reading package lists...
[2017-11-30 13:56:13]:  OK
[2017-11-30 13:56:13]:  Passed all requirements
[2017-11-30 13:56:15]:  Installing...
[2017-11-30 13:56:15]:  Starting Web Application Installation
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

**Comment by mondada** [comment]
Couple of quick Questions...
Was this originally an OVA appliance or built from a base OS and run file?
What happens when you run '_sudo apt-get -s upgrade_' are there a lot of updates to install?

**Comment by bbenkle** [comment]
only 2 updates were found:
linux-image-extra-4.4.0-91-generic : Depends: linux-image-4.4.0-91-generic but it is not installed
 linux-image-generic-lts-xenial : Depends: linux-image-4.4.0-91-generic but it is not installed

As for how this was originally setup, unfortunately the person who set it up no longer works for us. I reached out with the question and I hope to get back to you with a more definitive answer on how this was setup. 

Thanks for all your help!

**Comment by mondada** [comment]
On the surface it looks like an issue with Ubuntu resolving its dependency tree.
You seem to have a complete repo list.
Your system is up-to-date.
The only thing I can suggest is that you try performing each of the apt-get installs to pinpoint which ones are failing.
These are the individual install commands for each supporting component:
sudo apt-get install gawk
sudo apt-get install ufw
sudo apt-get install parted
sudo apt-get install whois
sudo apt-get install dialog
sudo apt-get install python-m2crypto
sudo apt-get install python-pycurl
sudo apt-get install libapache2-mod-php5
sudo apt-get install apache2-utils
sudo apt-get install php5-ldap
Do not attempt a force install of the failures, just let me know what they are.
Most of them should already be installed, the run skips them, which is why there aren't any log entries.
Its just not saying where it failed. May need to fix that.

**Comment by bbenkle** [comment]
**All commands returned:**
```
sudo apt-get install python-pycurl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pycurl is already the newest version.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 linux-image-extra-4.4.0-91-generic : Depends: linux-image-4.4.0-91-generic but it is not going to be installed
 linux-image-generic-lts-xenial : Depends: linux-image-4.4.0-91-generic but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```

**Except libapache2-mod-php5:**
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libapache2-mod-php5 is already the newest version.
libapache2-mod-php5 set to manually installed.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 linux-image-extra-4.4.0-91-generic : Depends: linux-image-4.4.0-91-generic but it is not going to be installed
 linux-image-generic-lts-xenial : Depends: linux-image-4.4.0-91-generic but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```

**Comment by mondada** [comment]
There are two concerning things here:
> libapache2-mod-php5 set to manually installed.
This can be corrected with:
apt-mark auto libapache2-mod-php5
> The reference to: linux-image-generic-lts-xenial
This seems to indicate that the system has been partially upgraded to Ubuntu 16, which opens a different can of worms, and will be a lot of fun to resolve.

**Comment by mondada** [comment]
* sudo apt-mark auto libapache2-mod-php5

**Comment by bbenkle** [comment]
Ran the sudo apt-get -f install​ command which gave an error regarding space issues. After running df -h​, I noticed /boot was at 100% due to the img files being populated with the upgrade. After moving older (4.4.0-[72,75,78,79,81,83]) img files to /tmp, I was able to run the upgrade successfully. The NetSUS installer was also then able to complete without any errors.
